const node = [
  "import { readFile, stat } from 'node:fs/promises'",
  '',
  "const api = 'https://api.domaindrop.dev/api/v1'",
  "const headers = { 'x-api-key': process.env.DOMAIN_DROP_API_KEY }",
  "const localFile = './august.pdf'",
  'const bytes = await readFile(localFile)',
  '',
  "const ticketResponse = await fetch(api + '/files/upload-url', {",
  "  method: 'POST',",
  "  headers: { ...headers, 'content-type': 'application/json' },",
  '  body: JSON.stringify({',
  '    spaceId: process.env.DOMAIN_DROP_SPACE_ID,',
  "    path: 'reports/august.pdf',",
  '    size: (await stat(localFile)).size,',
  "    mimeType: 'application/pdf',",
  '  }),',
  '})',
  'if (!ticketResponse.ok) throw new Error(await ticketResponse.text())',
  'const ticket = await ticketResponse.json()',
  '',
  "if (ticket.upload.type !== 'single') throw new Error('Use multipart flow')",
  'const uploaded = await fetch(ticket.upload.url, {',
  "  method: 'PUT',",
  '  headers: ticket.upload.headers,',
  '  body: bytes,',
  '})',
  'if (!uploaded.ok) throw new Error(await uploaded.text())',
  '',
  "const completed = await fetch(api + '/files/' + ticket.file.id + '/complete', {",
  "  method: 'POST',",
  "  headers: { ...headers, 'content-type': 'application/json' },",
  "  body: JSON.stringify({ parts: [{ partNumber: 1, etag: uploaded.headers.get('etag') }] }),",
  '})',
  'if (!completed.ok) throw new Error(await completed.text())',
  'console.log((await completed.json()).file)',
].join('\n')

const python = [
  'import os',
  'import requests',
  '',
  "api = 'https://api.domaindrop.dev/api/v1'",
  "auth = {'x-api-key': os.environ['DOMAIN_DROP_API_KEY']}",
  "local_file = './august.pdf'",
  '',
  "ticket_response = requests.post(f'{api}/files/upload-url', headers=auth, json={",
  "    'spaceId': os.environ['DOMAIN_DROP_SPACE_ID'],",
  "    'path': 'reports/august.pdf',",
  "    'size': os.path.getsize(local_file),",
  "    'mimeType': 'application/pdf',",
  '})',
  'ticket_response.raise_for_status()',
  'ticket = ticket_response.json()',
  '',
  "if ticket['upload']['type'] != 'single':",
  "    raise RuntimeError('Use multipart flow')",
  '',
  "with open(local_file, 'rb') as file:",
  "    uploaded = requests.put(ticket['upload']['url'], data=file, headers=ticket['upload']['headers'])",
  'uploaded.raise_for_status()',
  '',
  "completed = requests.post(f\"{api}/files/{ticket['file']['id']}/complete\", headers=auth, json={",
  "    'parts': [{'partNumber': 1, 'etag': uploaded.headers['ETag']}],",
  '})',
  'completed.raise_for_status()',
  "print(completed.json()['file'])",
].join('\n')

const java = [
  'import com.fasterxml.jackson.databind.*;',
  'import java.net.URI;',
  'import java.net.http.*;',
  'import java.nio.file.*;',
  'import java.util.*;',
  '',
  'var api = "https://api.domaindrop.dev/api/v1";',
  'var apiKey = System.getenv("DOMAIN_DROP_API_KEY");',
  'var file = Path.of("./august.pdf");',
  'var json = new ObjectMapper();',
  'var client = HttpClient.newHttpClient();',
  '',
  'var payload = json.writeValueAsString(Map.of(',
  '  "spaceId", System.getenv("DOMAIN_DROP_SPACE_ID"),',
  '  "path", "reports/august.pdf",',
  '  "size", Files.size(file),',
  '  "mimeType", "application/pdf"));',
  '',
  'var ticketRequest = HttpRequest.newBuilder(URI.create(api + "/files/upload-url"))',
  '  .header("x-api-key", apiKey)',
  '  .header("content-type", "application/json")',
  '  .POST(HttpRequest.BodyPublishers.ofString(payload)).build();',
  'var ticketResponse = client.send(ticketRequest, HttpResponse.BodyHandlers.ofString());',
  'if (ticketResponse.statusCode() >= 300) throw new RuntimeException(ticketResponse.body());',
  'var ticket = json.readTree(ticketResponse.body());',
  '',
  'var upload = ticket.get("upload");',
  'var putRequest = HttpRequest.newBuilder(URI.create(upload.get("url").asText()))',
  '  .header("content-type", "application/pdf")',
  '  .PUT(HttpRequest.BodyPublishers.ofFile(file)).build();',
  'var putResponse = client.send(putRequest, HttpResponse.BodyHandlers.discarding());',
  'var etag = putResponse.headers().firstValue("etag").orElseThrow();',
  '',
  'var completeBody = json.writeValueAsString(Map.of("parts", List.of(',
  '  Map.of("partNumber", 1, "etag", etag))));',
  'var completeUrl = api + "/files/" + ticket.get("file").get("id").asText() + "/complete";',
  'var completeRequest = HttpRequest.newBuilder(URI.create(completeUrl))',
  '  .header("x-api-key", apiKey).header("content-type", "application/json")',
  '  .POST(HttpRequest.BodyPublishers.ofString(completeBody)).build();',
  'System.out.println(client.send(completeRequest, HttpResponse.BodyHandlers.ofString()).body());',
].join('\n')

const go = [
  'package main',
  '',
  'import (',
  '  "bytes"',
  '  "encoding/json"',
  '  "fmt"',
  '  "io"',
  '  "net/http"',
  '  "os"',
  ')',
  '',
  'type Ticket struct {',
  '  File struct { ID string `json:"id"` } `json:"file"`',
  '  Upload struct { URL string `json:"url"`; Headers map[string]string `json:"headers"` } `json:"upload"`',
  '}',
  '',
  'func main() {',
  '  api := "https://api.domaindrop.dev/api/v1"',
  '  apiKey := os.Getenv("DOMAIN_DROP_API_KEY")',
  '  file, _ := os.Open("./august.pdf")',
  '  info, _ := file.Stat()',
  '  body, _ := json.Marshal(map[string]any{',
  '    "spaceId": os.Getenv("DOMAIN_DROP_SPACE_ID"),',
  '    "path": "reports/august.pdf", "size": info.Size(), "mimeType": "application/pdf",',
  '  })',
  '',
  '  req, _ := http.NewRequest("POST", api+"/files/upload-url", bytes.NewReader(body))',
  '  req.Header.Set("x-api-key", apiKey); req.Header.Set("content-type", "application/json")',
  '  response, err := http.DefaultClient.Do(req); if err != nil { panic(err) }',
  '  defer response.Body.Close()',
  '  var ticket Ticket; json.NewDecoder(response.Body).Decode(&ticket)',
  '',
  '  file.Seek(0, 0)',
  '  put, _ := http.NewRequest("PUT", ticket.Upload.URL, file)',
  '  for key, value := range ticket.Upload.Headers { put.Header.Set(key, value) }',
  '  uploaded, err := http.DefaultClient.Do(put); if err != nil { panic(err) }',
  '  io.Copy(io.Discard, uploaded.Body); uploaded.Body.Close()',
  '',
  '  complete, _ := json.Marshal(map[string]any{"parts": []any{',
  '    map[string]any{"partNumber": 1, "etag": uploaded.Header.Get("ETag")},',
  '  }})',
  '  done, _ := http.NewRequest("POST", api+"/files/"+ticket.File.ID+"/complete", bytes.NewReader(complete))',
  '  done.Header.Set("x-api-key", apiKey); done.Header.Set("content-type", "application/json")',
  '  result, err := http.DefaultClient.Do(done); if err != nil { panic(err) }',
  '  defer result.Body.Close(); output, _ := io.ReadAll(result.Body); fmt.Println(string(output))',
  '}',
].join('\n')

const rust = [
  'use reqwest::Client;',
  'use serde_json::{json, Value};',
  'use std::{env, path::Path};',
  'use tokio::fs;',
  '',
  '#[tokio::main]',
  'async fn main() -> Result<(), Box<dyn std::error::Error>> {',
  '  let api = "https://api.domaindrop.dev/api/v1";',
  '  let api_key = env::var("DOMAIN_DROP_API_KEY")?;',
  '  let local_file = Path::new("./august.pdf");',
  '  let bytes = fs::read(local_file).await?;',
  '  let client = Client::new();',
  '',
  '  let ticket: Value = client.post(format!("{api}/files/upload-url"))',
  '    .header("x-api-key", &api_key)',
  '    .json(&json!({',
  '      "spaceId": env::var("DOMAIN_DROP_SPACE_ID")?,',
  '      "path": "reports/august.pdf",',
  '      "size": bytes.len(),',
  '      "mimeType": "application/pdf"',
  '    })).send().await?.error_for_status()?.json().await?;',
  '',
  '  let uploaded = client.put(ticket["upload"]["url"].as_str().unwrap())',
  '    .header("content-type", "application/pdf")',
  '    .body(bytes).send().await?.error_for_status()?;',
  '  let etag = uploaded.headers().get("etag").unwrap().to_str()?;',
  '',
  '  let file_id = ticket["file"]["id"].as_str().unwrap();',
  '  let result: Value = client.post(format!("{api}/files/{file_id}/complete"))',
  '    .header("x-api-key", &api_key)',
  '    .json(&json!({ "parts": [{ "partNumber": 1, "etag": etag }] }))',
  '    .send().await?.error_for_status()?.json().await?;',
  '  println!("{}", result["file"]);',
  '  Ok(())',
  '}',
].join('\n')

const curl = [
  '# Requires curl and jq',
  'FILE=./august.pdf',
  'SIZE=$(stat -c%s "$FILE")',
  '',
  'TICKET=$(curl --fail --silent --request POST \\',
  '  https://api.domaindrop.dev/api/v1/files/upload-url \\',
  '  --header "x-api-key: $DOMAIN_DROP_API_KEY" \\',
  '  --header "content-type: application/json" \\',
  '  --data "{\\"spaceId\\":\\"$DOMAIN_DROP_SPACE_ID\\",\\"path\\":\\"reports/august.pdf\\",\\"size\\":$SIZE,\\"mimeType\\":\\"application/pdf\\"}")',
  '',
  'FILE_ID=$(echo "$TICKET" | jq -r .file.id)',
  'UPLOAD_URL=$(echo "$TICKET" | jq -r .upload.url)',
  '',
  'ETAG=$(curl --fail --silent --dump-header - --output /dev/null \\',
  '  --request PUT "$UPLOAD_URL" \\',
  '  --header "content-type: application/pdf" \\',
  '  --upload-file "$FILE" | awk -F\': \' \'tolower($1)=="etag" {gsub("\\r", "", $2); print $2}\')',
  '',
  'curl --fail --request POST \\',
  '  "https://api.domaindrop.dev/api/v1/files/$FILE_ID/complete" \\',
  '  --header "x-api-key: $DOMAIN_DROP_API_KEY" \\',
  '  --header "content-type: application/json" \\',
  '  --data "{\\"parts\\":[{\\"partNumber\\":1,\\"etag\\":\\"$ETAG\\"}]}"',
].join('\n')

export const languageExamples = {
  node: { label: 'Node.js', language: 'javascript', requirement: 'Node.js 20 or newer. No HTTP dependency is required.', code: node },
  java: { label: 'Java', language: 'java', requirement: 'Java 17 or newer with Jackson Databind for JSON.', code: java },
  go: { label: 'Go', language: 'go', requirement: 'Go 1.22 or newer. This example uses only the standard library.', code: go },
  python: { label: 'Python', language: 'python', requirement: 'Python 3.10 or newer with the requests package.', code: python },
  rust: { label: 'Rust', language: 'rust', requirement: 'Add tokio, reqwest, and serde_json to Cargo.toml.', code: rust },
  curl: { label: 'cURL', language: 'bash', requirement: 'The shell example uses curl, jq, awk, and GNU stat.', code: curl },
}
